### PR TITLE
Added support of Python 3

### PR DESCRIPTION
**Pull request by expobrain**
Adds support of Python 3 without breaking the support of Python 2

### CODE REVIEW

**Comment by andrehacker** [comment]
@expobrain could you please update your fork from upstream? Then the Travis CI test for the pull request should be green.

If you want you could already extend the the .travis.yaml file to test also Python 3. I did not look into this, but it should work relatively fine.

**Comment by expobrain** [comment]
@andrehacker thank you. I've just merged master and I'll have a look at the Travis config

**Comment by andrehacker** [comment]
Hi @expobrain, your changes in the travis config and the tests both seem to work fine, but now there seems to be a resources leak or so in Python 3 (almost same error for 3.5 and 3.6).
Do you have any idea what could have caused this? If you don't have time we could try to check from our side.

**Comment by expobrain** [comment]
@andrehacker not yet, I need to investigate what's happening during `test_readData_defaults_to_pandas()` and `test_writeData_defaults_to_pandas` which got stuck during the tests

**Comment by andrehacker** [comment]
Hi @expobrain, I guess you did not find time to look into this. In case you are still motivated to look at this let us know, otherwise we will have a look at it. Thanks for your input so far.

**Comment by expobrain** [comment]
Hi @andrehacker, totally forgot about this. I'll have a look at it soon

**Comment by Ashafix** [comment]
Any ideas why the Python 3.6 but not 3.5 is failing? Code looks OK. Perhaps we could add yet another `try/except` clause?

**Comment by expobrain** [comment]
@Ashafix when I was trying to fix the issue I found out that there's some kind of inverted order to close pipes in Python 3.5 compared to 3.6 and 2.7.

I didn't continue my test because at the end we switched to https://github.com/badoo/pyexasol.

**Comment by andrehacker** [comment]
Changes from this PR were used in #10 , now merged.

**Pull request closed without merging**
